name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Build
      run: |
        GOOS=windows GOARCH=amd64 go build .
    - uses: actions/upload-artifact@v2
      with: 
        name: awinadb
        path: awinadb.exe